### ISSUE TITLE
Feature Request: Split up alchemy-related collections to a meta-only database

### ISSUE THREAD

**Issue by KennethGomez** [ForetagInc/Alchemy#12]
### Preliminary checklist

- [X] I understand that all communication must be in English
- [X] I read the [Documentation](https://engineering.foret.ag)
- [X] I read the [Contributing guide](https://github.com/ForetagInc/.github/blob/master/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/ForetagInc/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I searched the issues and discussions but couldn't find anything (or linked relevant results below)

### Problem

Right now all the meta-data related to the Alchemy instance is on the same database as the `real` data is. 

This is a problem in case of overlapping between table names and entities, for example, if someone creates an entity called AlchemyCollection (for some reason their project needs this name) there would be an error as the collection name generated after this would be `alchemy_collections` which is already reserved for the Alchemy instance meta-data.

### Solution

The solution for this is to create another database with the name `_{name}_meta`, so, for example, if a database is called `game`, its meta-data database is gonna be `_game_meta`.

This new database is where all the Alchemy-related collections are gonna be stored. This fixes the overlapping issue between collection names and also isolates the real information from the Alchemy data which may help some projects to migrate their data or other things.

### Alternatives

The problem could also be solved by instead of using ArangoDB as the medium to store meta-data-related information, using another storage system such as files. This could also work as the meta-data information Alchemy handles is not big, so there wouldn't be any issues with this system.

### Contribution

Yes

### Keywords

integration, meta

**Comment by itsezc** [comment]
A few pointers:

- Arango collection names have to start with the alphabet
- It would be best if we stick to one database to not over use threads available in the environment
- Where there are duplicate collection names, we could do one of the either:
  -  Use aliases
  -  Increment collection names i.e. if `alchemy_collections` exist, then use `alchemy2_collections`
